### ISSUE TITLE
Not working anymore!

### ISSUE THREAD

**Issue by ybreza** [xNasuni/adobefirefly-downloader#3]
I have tried it repeatedly using the universal-main.js file but the response issued on the console is ...

_[VM210:87 Uncaught (in promise) 
TypeError: Canvas.toDataURL is not a function
    at DownloadCanvas (<anonymous>:87:36)
    at <anonymous>:97:9
    at <anonymous>:121:3]_

Maybe Adobe has updated some HTML/JS tags so they can no longer be read by the script.
[![https://i.postimg.cc/Jz7RL4vZ/Cuplikan-layar-2024-06-01-204447.jpg]()](https://i.postimg.cc/Jz7RL4vZ/Cuplikan-layar-2024-06-01-204447.jpg)

**Comment by xNasuni** [comment]
checking it out right now.

**Comment by xNasuni** [comment]
found a fix, publishing in a minute

**Comment by xNasuni** [comment]
resolution: the website's UI changed and the old function to get the canvas (GetCanvas) couldn't find the canvas where the drawing was, I have changed it to a new function that matches the current markup and from my testing does get the canvas properly.

please re-open if you still have issues.
